# Generated by Django 6.1.1 on 2026-10-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DutyStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=4)),
                ('start_minute', models.PositiveSmallIntegerField()),
                ('end_minute', models.PositiveSmallIntegerField()),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.dailylog')),
            ],
        ),
    ]
